name: accounting
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: Setup Dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '6.0.x'
            - name: Copy proto file
              run: cp pb/demo.proto src/accounting/proto/demo.proto