name: Build and Test Ad Service
on: [push]
    # push:
    #     paths:
    #         - 'src/ad/**'
    # pull_request: 
    #     paths:
    #         - 'src/ad/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: install java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'
          - name: Copy protofile
            run: |
                mkdir -p src/ad/proto
                cp pb/demo.proto src/ad/proto/demo.proto
          - name: DownloadRepos
            run: |
                cd src/ad
                chmod +x ./gradlew
                ./gradlew downloadRepos