name: Build and Test Ad Service
on: [push]
    # push:
    #     paths:
    #         - 'src/ad/**'
    # pull_request: 
    #     paths:
    #         - 'src/ad/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: install java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'
          - name: Copy protofile
            run: |
                mkdir -p src/ad/proto
                cp pb/demo.proto src/ad/proto/demo.proto
          - name: DownloadRepos
            run: |
                cd src/ad
                chmod +x ./gradlew
                ./gradlew downloadRepos
          - name: install Dist
            run: | 
                cd src/ad
                chmod +x ./gradlew
                ./gradlew installDist -PprotoSourceDir=./proto

    docker-build-push:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: CheckoutCode
              uses: actions/checkout@v4
            - name: install Docker
              uses: docker/setup-buildx-action@v3
            - name: Dockerhub login
              uses: docker/login-action@v3
              with:
               username: ${{ vars.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: build and push image
              uses: docker/build-push-action@v6
              with:
                 context: .
                 file: 'src/ad/Dockerfile'
                 push: true
                 tags: isansharma/adservice
            - name: Run Trivy vulnerability scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: isansharma/accountingservice:${{ github.run_number }}
                format: 'table'
                exit-code: '1'              # Fail the workflow on high/critical issues
                ignore-unfixed: true        # Optional: skip unfixed vulnerabilities
                severity: 'CRITICAL,HIGH' 

              