name: Cart Service
on:
 push:
    paths:
      - 'src/cart/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Copy pb file
        run: |
            mkdir -p src/accounting/proto
            cp pb/demo.proto src/accounting/proto/demo.proto
      - name: Restore Dependencies
        run: |
            dotnet restore src/cart/src/cart.csproj
      - name: Build Project
        run: |
            dotnet build src/cart/src/cart.csproj
      - name: Test code
        run: |
            dotnet test src/cart/tests/cart.tests.csproj --no-build --verbosity normal
    
  docker:    
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: set up docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/cart/src/Dockerfile
          push: true
          tags: isansharma/cartservice:${{ github.run_number }}
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: isansharma/cartservice:${{ github.run_number }}
          format: 'table'
          exit-code: '1'              # Fail the workflow on high/critical issues
          ignore-unfixed: true        # Optional: skip unfixed vulnerabilities
          severity: 'CRITICAL,HIGH'